### PR TITLE
Compatibility with Cascading 3.0 take two

### PR DESCRIPTION
**Pull request by rubanm**
Picks up from https://github.com/twitter/elephant-bird/pull/454/

- common code moved to cascading-protobuf (looks like neither cascading2 nor cascading3 actually depend on it)
- removed deprecated schemes from being ported

So far, I've only verified scalding develop compiles against this branch i.e. no regression in the cascading2 codepath.

cc @cchepelov @ianoc @johnynek

### CODE REVIEW

**Comment by rubanm** [comment]
Fixed some of the InputFormat changes from previous branch. This passes Twitter internal e2e tests now.

Given we have good confidence there's no regression in the cascading2 codepath, I propose merging this if there are no more edits needed. Cascading3 changes are going to be e2e tested separately with a 3.0 branch in Scalding.

**Comment by johnynek** [comment]
:+1:

**Comment by cchepelov** [comment]
@rubanm this is great! Thanks

How far do you think we are from an elephant-bird release now? 



Le 8 févr. 2016 20:38, à 20:38, Ruban Monu <notifications@github.com> a écrit:

**Comment by rubanm** [comment]
Released a new version a short while back https://github.com/twitter/elephant-bird/releases/tag/elephant-bird-4.13

**Pull request merged**
