### PR TITLE
Added condition to fetch serialization class for a presto query

### PR DESCRIPTION
**Pull request by Yaliang**
Presto set the serialization class property directly on jobConfig.

### CODE REVIEW

**Comment by Yaliang** [comment]
@isnotinvain / @gerashegalov can I get a quick review?

**Comment by gerashegalov** [comment]
LGTM, @Yaliang. 👍

**Comment by Yaliang** [comment]
Can I kindly ask a merge from someone with write access? Thanks @isnotinvain @rubanm

**Comment by rubanm** [comment]
@Yaliang Sorry I don't have merge access anymore :( cc @piyushnarang @benpence

**Pull request merged**
