### PR TITLE
Faster working with LzoBinary data

### PR DESCRIPTION
**Pull request by ianoc**
Use a thread pool for reading lzo indexes can cut launch time for a job from several minutes to the low seconds.

### CODE REVIEW

**Comment by gerashegalov** [comment]
Changes in LzoInputFormat duplicate my work in #434 while providing less RPC savings. I would not put multithreaded status fetch in eb because Hadoop 2.3+ already provides it.

**Comment by ianoc** [comment]
The main win for us has been reading the index in parallel, not actually getting the status that I've seen. Our PR's are independent from each other in effect no?

**Comment by gerashegalov** [comment]
I see, then we can compose PR's nicely. Reading index in parallel cannot be pushed into hadoop FileInputFormat. With #434 we can submit index file reads to an LzoInputFormat thread pool from listStatus only when they exist, and harvest the results in getSplits

**Comment by rangadi** [comment]
This was done earlier. One of the issues was total memory required to keep the whole index in memory (we can't). We could avoid this with a limit on indexes buffered. I will check why that patch finally didn't make it.

**Pull request merged**
